#!/bin/bash

# Will be executed as user "root".

# Name this file "daemon.sh" in your plugin-archive. It will be renamed to NAME
# during installation

pluginname=$(basename $0 .sh)

if [ -x /usr/bin/logger ]; then
    /usr/bin/logger "loxberry-plugin-$pluginname - DAEMON Script from RCSwitch Plugin"
fi

# Create sudoers file
if [ -x /usr/bin/logger ]; then 
	/usr/bin/logger "loxberry-plugin-$pluginname - Adding sudoers permissions"
fi
chmod 0640 /etc/sudoers.d/$pluginname
echo %loxberry ALL = NOPASSWD: REPLACEINSTALLFOLDER/data/plugins/$pluginname/bin/send433 > /etc/sudoers.d/$pluginname
echo %loxberry ALL = NOPASSWD: /etc/init.d/pilight >> /etc/sudoers.d/$pluginname
chmod 0440 /etc/sudoers.d/$pluginname
chmod 0755 REPLACEINSTALLFOLDER/data/plugins/$pluginname/bin/send433

# Installing pilight
if [ ! -x /usr/local/sbin/pilight-daemon ]; then
  if [ -x /usr/bin/logger ]; then 
	/usr/bin/logger "loxberry-plugin-$pluginname - Installing pilight - please be patient..."
  fi
  echo "deb http://apt.pilight.org/ stable main" > /etc/apt/sources.list.d/pilight.list
  /usr/bin/wget -O - http://apt.pilight.org/pilight.key | apt-key add -
  /usr/bin/apt-get update
  /usr/bin/apt-get -y install pilight
fi

# Configure pilight
if [ -x /usr/bin/logger ]; then 
	/usr/bin/logger "loxberry-plugin-$pluginname - Configuring pilight"
fi
if [ -d /etc/pilight ]; then
  service pilight stop
  mv /etc/pilight /etc/pilight.orig
  ln -s REPLACEINSTALLFOLDER/config/plugins/$pluginname/pilight /etc/pilight
  service pilight start
fi

exit 0
